version: "3.3"

services:

  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log
    depends_on:
      - php
      - database

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=8.0
      - XDEBUG_CONFIG="client_host=192.168.220.1"
      - PHP_IDE_CONFIG="serverName=Docker"
    volumes:
      - ./src:/var/www/html:delegated
      - ./php/php.ini:/usr/local/etc/php/php.ini

  console:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=8.0
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "php", "/var/www/html/bin/console" ]

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "2200:3306"
